### ISSUE TITLE
Deleting old programs and (JETZT!) doesn't work anymore in 0.7.0

### ISSUE THREAD

**Issue by TheVaan** [timoschlueter/RocketBeans.TV-Sendeplan#9]
It worked with 0.7.0 (I have a screenshot from 24.01., 22:33). Same code, one hour later: "(JETZT!)" indicator is **not** showing and old programs are **not** deleted!

Deleted my local repo und pulled it again, still doesn't work.

**Comment by der-tkw** [comment]
#7 is the reason. #8 should fix that.

**Comment by TheVaan** [comment]
Pulled your code. Problem still exists. I don't know why, but I think it's a local problem...

**Comment by TheVaan** [comment]
After some debugging I finally found the problem:
![bildschirmfoto 2015-01-25 um 02 06 17](https://cloud.githubusercontent.com/assets/1108485/5889757/056b071c-a437-11e4-8568-c4a434cfecca.png)

It seems that the problem only occurs between 00:05 and 02:35.
![bildschirmfoto 2015-01-25 um 02 36 56](https://cloud.githubusercontent.com/assets/1108485/5889836/2d1b1a64-a43b-11e4-8336-cd4065a071e6.png)

I don't know why, but the endDate had to many information. I was not able until 02:35 to fix it - to late for coding.

**Comment by der-tkw** [comment]
I think it's a timezone issue as well. I will take a look at this later today. Maybe it makes more sense to fetch the google calendar with original information and apply the timezone later in order to avoid those strange cases.

**Comment by der-tkw** [comment]
To conclude this: parsing dates from strings isn't fun. Google doesn't provide a good way to retrieve the calendar data. It's either XML, JSON or iCal. XML and JSON doesn't contain real date fields, just the shitty summary with strange information that needs to be parsed. And since I couldn't find a quick and easy way to parse iCal in Cocoa I don't know what to do anymore. It's basically not easily possible to parse dates correctly and therefore provide a stable solution to determine the current program. And if there is no current program, the deleting of old programs also becomes buggy.

For the sake of completeness: the browser extensions are all using some kind of manual regex parser for the  iCal file.

So #8 will improve the situation, but it will leave situations where the algorithm fails.

**Comment by der-tkw** [comment]
Improved date parsing algorithm, your case is now handled as well. However I'm not sure if there can occur many other cases in Google's strange summary date strings. Let's hope for the best.

**Comment by TheVaan** [comment]
If there are more of these problemes:
Whats about getting endDateStr by taking the last 5 characters?

Something like

endDate = programDate.substringFromIndex(advance(-5,5))

Or by splitting at each " " and taking the last item in the split array.

**Comment by der-tkw** [comment]
I guess that would work as well, however the most cases should be covered now.

**Comment by der-tkw** [comment]
#8 fixed this issue. Should be closed.

**Comment by timoschlueter** [comment]
Fixed again in 072eb22943930e818a5e2d4484f1366137f321f3.
